
export default [
  { title:'id', field: 'nrcrt', defaultSort:'desc' },
  { title:'idComanda', field: 'idComanda'},
  { title:'nrCrt', field: 'nrCrt'},
  { title:'tipSubprodus', field: 'nrCrt'},
  { title:'lungime', field: 'nrCrt'},
  { title:'lungimeFinala', field: 'nrCrt'},
  { title:'inaltime', field: 'nrCrt'},
  { title:'inaltimeFinala', field: 'nrCrt'},
  { title:'deschidere', field: 'nrCrt'},
  { title:'culoareLamela', field: 'nrCrt'},
  { title:'culoareCaseta', field: 'nrCrt'},
  { title:'material', field: 'nrCrt'},
  { title:'codMaterial', field: 'nrCrt'},
  { title:'lungimeSnur', field: 'nrCrt'},
  { title:'actionare', field: 'nrCrt'},
  { title:'tipActionare', field: 'nrCrt'},
  { title:'actionareStDr', field: 'nrCrt'},
  { title:'ax', field: 'nrCrt'},
  { title:'culoareComponente', field: 'nrCrt'},
  { title:'optional1', field: 'nrCrt'},
  { title:'optional2', field: 'nrCrt'},
  { title:'optional3', field: 'nrCrt'},
  { title:'console', field: 'nrCrt'},
  { title:'buc', field: 'nrCrt'},
  { title:'mp', field: 'nrCrt'},
  { title:'pretCatalog', field: 'nrCrt'},
  { title:'pretCuDiscount', field: 'nrCrt'},
  { title:'pretClientFinal', field: 'nrCrt'},
  { title:'observatii', field: 'nrCrt'},
  { title:'tipProdus', field: 'nrCrt'},
  { title:'created_at', field: 'nrCrt'},
  { title:'updated_at', field: 'nrCrt'},
  { title:'denumireProdus', field: 'nrCrt'},
  { title:'denumireSubProdus', field: 'nrCrt'},
  { title:'denumireCuloareLamela', field: 'nrCrt'},
  { title:'denumireCuloareCaseta', field: 'nrCrt'},
  { title:'denumireMaterial', field: 'nrCrt'},
  { title:'denumireTipActionare', field: 'nrCrt'},
  { title:'denumireOptional1', field: 'nrCrt'},
  { title:'denumireOptional2', field: 'nrCrt'},
  { title:'denumireOptional3', field: 'nrCrt'},
  { title:'fotografii', field: 'nrCrt'},
];